Polish translation
acidicoala/Koalageddon2 pull request #11
Opened 2023-06-08 17:46 UTC by WujekFoliarz

2023-06-30 08:54 UTC, NikNikovsky commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        modifyInstallation = "Modyfikuj instalacje",
Modyfikuj instalację*

2023-06-30 08:54 UTC, NikNikovsky commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        openLatestReleasePage = "Przejdź na witryne programu",
Przejdź na stronę programu*

2023-06-30 08:55 UTC, NikNikovsky commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        restoreDefaultConfiguration = "Przywróć domyślną konfiguracje",
Przywróć domyślną konfigurację

2023-06-30 08:56 UTC, NikNikovsky requested changes
there is some stuff to fix in my opinion, feel free to check and let me know

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        autoInjectInventory = "Automatycznie wstrzyknij przedmioty do ekwipunku steam w grze",
autoInjectInventory = "Automatycznie wprowadź przedmioty do ekwipunku Steam wewnątrz gry.",

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        extraInventoryItems = "Wstrzyknij przedmioty do ekwipunku steam w grze",
extraInventoryItems = "Wprowadź przedmioty do ekwipunku steam wewnątrz gry",

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        inDevelopment = "Już niedługo",
inDevelopment = "W trakcie rozwoju",

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        openOfficialForumTopic = "Przejdź do oficjalnego forum",
openOfficialForumTopic = "Przejdź do oficjalnego wątku na forum",

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        overrideAppStatus = "Wymuś stan gry",
overrideAppStatus = "Nadpisz stan gry",

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        overrideDlcStatus = "Wymuś stan DLC",
overrideDlcStatus = "Nadpisz stan DLC",

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        theme = "Kolor tła",
theme = "Motyw",

2024-01-23 22:13 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        remove = "Odinstaluj",
remove = "Usuń",

2024-01-23 22:22 UTC, magik-9 requested changes

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        autoInjectInventory = "Automatycznie wstrzyknij przedmioty do ekwipunku steam w grze",
autoInjectInventory = "Automatycznie wprowadź przedmioty do ekwipunku Steam wewnątrz gry.",

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        extraInventoryItems = "Wstrzyknij przedmioty do ekwipunku steam w grze",
extraInventoryItems = "Wprowadź przedmioty do ekwipunku steam wewnątrz gry",

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        inDevelopment = "Już niedługo",
inDevelopment = "W trakcie rozwoju",

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        openOfficialForumTopic = "Przejdź do oficjalnego forum",
openOfficialForumTopic = "Przejdź do oficjalnego wątku na forum",

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        overrideAppStatus = "Wymuś stan gry",
overrideAppStatus = "Nadpisz stan gry",

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        overrideDlcStatus = "Wymuś stan DLC",
overrideDlcStatus = "Nadpisz stan DLC",

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        theme = "Kolor tła",
theme = "Motyw",

2024-01-23 22:22 UTC, magik-9 commented on src/jvmMain/kotlin/acidicoala/koalageddon/core/values/Strings.kt
> +        remove = "Odinstaluj",
remove = "Usuń",

2024-01-23 23:20 UTC, NikNikovsky commented
I agree with all changes, will fix soon

2024-06-17 08:33 UTC, BigBOSSo commented
![image (15)](https://github.com/acidicoala/Koalageddon2/assets/19314407/1b0cb30b-825a-45b7-9d9f-b8dda09c8ad6)
Stopped working

2025-09-03 12:17 UTC, acidicoala commented
Closing due to this project being archived.

2025-09-03 12:17 UTC, closed without merging